Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "generic/ubuntu2204"
      node.vm.hostname = "node#{i}"
      node.vm.network "public_network", ip: "192.168.0.#{41+i}", bridge: "public_network"
    end
  end

  config.vm.provider "hyperv" do |hv|
    hv.memory = "2048"
  end
end
