---
- name: Update system packages
  hosts: webservers
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        name: '*'
        update_cache: yes
        cache_valid_time: 3600
        state: latest
    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
